# Generated by Django 4.1.6 on 2023-05-13 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemId', models.CharField(max_length=100)),
                ('borrowNum', models.IntegerField()),
                ('borrowTime', models.DateTimeField(auto_now_add=True)),
                ('returnNum', models.IntegerField(default=0)),
                ('isOver', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipId', models.CharField(default='0', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('totalNum', models.IntegerField(default=0)),
                ('borrowNum', models.IntegerField(default=0)),
                ('location', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returnNum', models.IntegerField()),
                ('returnTime', models.DateTimeField(auto_now_add=True)),
                ('borrowHistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returnHistorys', to='equipment.borrowhistory')),
                ('returnUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
