# Generated by Django 4.1.6 on 2023-06-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipmentmodification'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentmodification',
            name='user_firstname',
            field=models.TextField(blank=True, null=True),
        ),
    ]
